version: "3.9"

services:
  nats:
    image: nats:2.10
    ports:
      - "4222:4222"
      - "8222:8222"

  server-rs:
    build:
      context: ./server-rs
    environment:
      HTTP_PORT: "8080"
      NATS_URL: "nats://nats:4222"
      NATS_SUBJECT: "ticks"
    depends_on:
      - nats
    ports:
      - "8080:8080"

  producer:
    build:
      context: ./producer
    environment:
      NATS_URL: "nats://nats:4222"
      NATS_SUBJECT: "ticks"
    depends_on:
      - nats