// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CustomDatetimeFormat } from "./CustomDatetimeFormat.js";
import type { FormatUnit } from "./FormatUnit.js";

export type CustomDatetimeStyleConfig = { format: FormatUnit, timeZone?: string | null, fractionalSecondDigits?: number, second?: CustomDatetimeFormat, minute?: CustomDatetimeFormat, hour?: CustomDatetimeFormat, day?: CustomDatetimeFormat, weekday?: CustomDatetimeFormat, month?: CustomDatetimeFormat, year?: CustomDatetimeFormat, hour12?: boolean, };
