// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RoundingMode } from "./RoundingMode.js";
import type { RoundingPriority } from "./RoundingPriority.js";
import type { SignDisplay } from "./SignDisplay.js";
import type { TrailingZeroDisplay } from "./TrailingZeroDisplay.js";
import type { UseGrouping } from "./UseGrouping.js";

export type CustomNumberFormatConfig = { minimumIntegerDigits: number | null, minimumFractionDigits: number | null, maximumFractionDigits: number | null, minimumSignificantDigits: number | null, maximumSignificantDigits: number | null, roundingPriority: RoundingPriority | null, roundingIncrement: number | null, roundingMode: RoundingMode | null, trailingZeroDisplay: TrailingZeroDisplay | null, useGrouping: UseGrouping | null, signDisplay: SignDisplay | null, };
