// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CustomDatetimeStyleConfig } from "./CustomDatetimeStyleConfig.js";
import type { SimpleDatetimeStyleConfig } from "./SimpleDatetimeStyleConfig.js";

/**
 * `Simple` case has all default-able keys and must be last!
 */
export type DatetimeFormatType = CustomDatetimeStyleConfig | SimpleDatetimeStyleConfig;
