// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Scalar } from "./Scalar.js";

export type FilterTerm = Array<Scalar> | Scalar;
