// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * This type represents the ViewConfig serializable type, which must be JSON
 * safe.
 */
export type Scalar = number | string | boolean | null;
