// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SimpleDatetimeFormat } from "./SimpleDatetimeFormat.js";

export type SimpleDatetimeStyleConfig = { timeZone?: string | null, dateStyle?: SimpleDatetimeFormat, timeStyle?: SimpleDatetimeFormat, };
