// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * View types
 */
export type ColumnType = "string" | "date" | "datetime" | "integer" | "float" | "boolean";
