// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Options for [`Table::delete`].
 */
export type DeleteOptions = { lazy: boolean, };
