// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ViewOnUpdateResp } from "./ViewOnUpdateResp.js";

/**
 * Rows updated and port ID corresponding to an update batch, provided to the
 * callback argument to [`View::on_update`] with the "rows" mode.
 */
export type OnUpdateData = ViewOnUpdateResp;
