// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OnUpdateMode } from "./OnUpdateMode.js";

/**
 * Options for [`View::on_update`].
 */
export type OnUpdateOptions = { mode: OnUpdateMode | null, };
