// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The update mode for [`View::on_update`].
 *
 * `Row` mode calculates and provides the update batch new rows/columns as an
 * Apache Arrow to the callback provided to [`View::on_update`]. This allows
 * incremental updates if your callbakc can read this format, but should be
 * disabled otherwise.
 */
export type OnUpdateMode = "row";
