// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The format to interpret data preovided to [`Client::table`].
 *
 * When serialized, these values are `"csv"`, `"json"`, `"columns"`, `"arrow"`
 * and `"ndjson"`.
 */
export type TableReadFormat = "csv" | "json" | "columns" | "arrow" | "ndjson";
