// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TableReadFormat } from "./TableReadFormat.js";

/**
 * Options for [`Table::update`].
 */
export type UpdateOptions = { port_id: number | null, format: TableReadFormat | null, };
