// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Options for serializing a window of data from a [`View`].
 *
 * Some fields of [`ViewWindow`] are only applicable to specific methods of
 * [`View`].
 */
export type ViewWindow = { start_row?: number, start_col?: number, end_row?: number, end_col?: number, id?: boolean, index?: boolean, leaves_only?: boolean, 
/**
 * Only impacts [`View::to_csv`]
 */
formatted?: boolean, 
/**
 * Only impacts [`View::to_arrow`]
 */
compression?: string, };
